name: Tag and Release

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      release_notes:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of Golang package to release'
        required: true
        type: string
      release_notes:
        description: 'Release notes for the version'
        required: true
        type: string

permissions:
  contents: write

jobs:
  tag-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Validate version format for Go module
        run: |
          VERSION="${{ inputs.version }}"
          if [[ ! "$VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9.\-]+)?(\+[a-zA-Z0-9.\-]+)?$ ]]; then
            echo "Invalid version format for Go module: $VERSION"
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Create tag
        run: |
          git tag "${{ inputs.version }}"
          git push origin "${{ inputs.version }}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.version }}
          name: Release ${{ inputs.version }}
          body: ${{ inputs.release_notes }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}